### ISSUE TITLE
Dice Roller

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#32]
Dice roller, likely via the roll npm package, which rolls dice based on dice notation. i.e. <number of dice>d<number of dice sides>, math support, and best x of rolled. So **3D20B2   2** results in **[12, ~~5~~, 13] => 12 13 2 = 27**. Bonus for implementing yes

**Comment by DomtronVox** [comment]
aww cut it off, also lost the bits I put between "<>" which is why there is a solitary d there. last part was about yes-no-maybe results like what https://top.gg/bot/464728785107812352 implements. where a roll returns like 7 different answers ranging from
* yes
* yes, but...
* yes, and...
* maybe
* and the negative versions of the first 3

**Comment by SkyeRangerDelta** [comment]
Yeah, that command's delimiters is a hyphen, the `yes-no-maybe` is what broke it. I got the idea though. I'll be working on this for 1.17.6.

**Comment by SkyeRangerDelta** [comment]
Added in V1.17.6.
