### ISSUE TITLE
Suggestion: Add helptext for each command 

### ISSUE THREAD

**Issue by Gman217** [SkyeRangerDelta/Fishsticks#5]
There should be documentation offerings for every declaration of !commandname ?  And/or !commandname -help (or !commandname help, unless/until this is standardized)

**Comment by SkyeRangerDelta** [comment]
There is a command already for this; `!codex [commandID]`

Currently in the works, but has an entry for the most recent !role command.

**Comment by Gman217** [comment]
Can this be aliased to !commandname ? Or !commandname help to fit industry standards? :P

**Comment by SkyeRangerDelta** [comment]
No, !codex is a catch all I had meant to implement earlier (way earlier) in development. Codex works similarly to a regular active command in that it searches for an entry based on input; leaving it open for more than just command help.

Essentially, why go through all the commands and add an extra parameter when you can expend the same amount of time to open Fishsticks' "encyclopedia" of sorts.

**Comment by Gman217** [comment]
Because that's how virtually every mod/bot/chat help utility ever does it.  You have your full documentation, and then you have your quick reference calls.  Remember the Nanite mod in Space Engineers? Also, Battle.net does it this way, virtually every MMO does it this way, etc.

If I remember the command, but I can't remember the parameters or syntax specifics, the first place my mind goes is the ? Or help parameter of that command, not a whole different command.  I would expect this is true of most people, and is generally considered an industry best practice.

**Comment by Gman217** [comment]
In other words, ideally, it would work both ways.

**Comment by SkyeRangerDelta** [comment]
Re-opening this request and queuing it for implementation.

Each command will be looked over for enhanced responses instead of "don't be stupid." Help documentation will still be resorted to in the Codex, but if the command encounters an error, Fishsticks should inform the command issuer of what they did instead of...not doing that.

Codex commands will also come with a link to the wiki section for that command in the embed.

**Comment by SkyeRangerDelta** [comment]
Finally, this issue is finished. All commands now have a much greater information factor when something goes awry. All 42 of them. Fishsticks' won't just say 'something dumb has occurred' or something similar (unless of course something entirely unknown has happened).

If someone encounters an error that was vague, they can use `!suggest` to open an issue, or just inform me.
