### ISSUE TITLE
hosting requirements

### ISSUE THREAD

**Issue by pcnate** [SkyeRangerDelta/Fishsticks#53]
Are the basic requirements documented for hosting a test version?

Things like, what database to run and is there a setup script or list of required tables/entities to exist in said database?

**Comment by SkyeRangerDelta** [comment]
There is no test version aside from the development stream on any machine running the dev environment.

FSO runs off of a MySQL db (RethinkDB starting in V18) but the config files for both API connections and whatnot are kept in files not kept on GitHub.

Really no test version is meant to be run because...well, development isn't exactly open.

**Comment by pcnate** [comment]
So the js source is accessible but the database sources are closed?

**Comment by SkyeRangerDelta** [comment]
Correct.

Code is public, accessibility isn't. I've been debating pulling the repo itself for quite some time.

**Comment by pcnate** [comment]
Well I ask because here and there I get the urge to help with things.

**Comment by SkyeRangerDelta** [comment]
I'll DM you later on how we might collab, been super busy recently, and that likely won't change for about a week.

**Comment by pcnate** [comment]
No rush. Just saw #52 and thought if I could host a test version of FS I take a look at that

**Comment by SkyeRangerDelta** [comment]
I hate testing the API for that one and the upcoming define command because they have limited API calls per month. Not that we'd hit them but still.

**Comment by pcnate** [comment]
I assume that you mean an API to a bible site?

**Comment by SkyeRangerDelta** [comment]
Why do that, when I can just use an API.
